services:
  backend:
    build: ./backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - host_ollama=http://host.docker.internal:11434

  client:
    build: ./frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VITE_REACT_APP_URL=
    depends_on:
      - backend

  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - client
