services:
  backend:
    image: ghcr.io/npi-true/english-tutor-backend:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - host_ollama=http://host.docker.internal:11434

  client:
    image: ghcr.io/npi-true/english-tutor-frontend:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend

  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/ssl/certs/
    depends_on:
      - backend
      - client
