services:
  backend:
    build: ./backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - host_ollama=http://${MY_IP}:11434
    networks:
      - app-network

  client:
    build: ./frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VITE_REACT_APP_URL=https://${MY_IP}
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - backend
      - client

networks:
  app-network:
    driver: bridge
