services:
  server:
    build: ./backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - host_ollama=http://${MY_IP}:11434
    ports:
      - "7123:7123"
    networks:
      - app-network

  client:
    build: ./frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - VITE_REACT_APP_URL=http://${MY_IP}
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:
    driver: bridge
